libreorganize/apps/accounts/urls.py
from django.urls import path, re_path
from django.contrib.auth.views import PasswordResetConfirmView, PasswordResetCompleteView, PasswordResetDoneView
from django.views.generic import TemplateView

from apps.accounts import views, forms

app_name = 'apps.accounts'

urlpatterns = [
    path('login/', views.login_view, name='login'),

    path('logout/', views.logout_view, name='logout'),

    path('register/', views.register_view, name='register'),

    re_path(r'^password/change/(?P<id>\d+)/$', views.password_change_view, name='change_password'),

    re_path(r'^password/change/done/(?P<id>\d+)/$', views.password_change_done_view, name='change_password_done'),

    path('password/reset/', views.password_reset_view, name='reset_password'),

    re_path(r'^password/reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$',
            PasswordResetConfirmView.as_view(template_name='registration/custom_password_reset_confirm.html', form_class=forms.PasswordChangeForm),
            name='reset_password_confirmation'),

    path('password/reset/complete/', PasswordResetCompleteView.as_view(template_name='registration/custom_password_reset_complete.html'),
         name='reset_password_complete'),

    path('password/reset/done/', PasswordResetDoneView.as_view(template_name='registration/custom_password_reset_done.html'),
         name='reset_password_done'),

    path('register/complete/', TemplateView.as_view(template_name='accounts/registration_complete.html'),
         name='register_complete'),
]

libreorganize/core/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name="home.html"), name='home'),
    path('accounts/', include('apps.accounts.urls', namespace='accounts')),
    re_path(r'^captcha/', include('captcha.urls')),
]

libreorganize/apps/accounts/models.py
from django.conf import settings
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User

libreorganize/apps/accounts/forms.py
import re

from django import forms
from django.conf import settings
from django.contrib.auth.models import User
from django.contrib.auth.forms import SetPasswordForm
from django.contrib.auth import authenticate, login
from django.contrib import messages
from django.utils.translation import gettext_lazy as _
from django.utils.safestring import mark_safe
from django.contrib.auth.tokens import default_token_generator
from django.template import loader
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode

from captcha.fields import CaptchaField
from django_countries.fields import CountryField

from captcha.fields import CaptchaTextInput
from timezone_field import TimeZoneField
import pytz
TIMEZONES = tuple(zip(pytz.all_timezones, pytz.all_timezones))
#from apps.profiles.models import Profile
#from apps.accounts.models import RegistrationProfile
#from apps.accounts.utils import send_registration_activation_email
#from apps.emails.models import Email


class LoginForm(forms.Form):

    user = None

    username = forms.CharField(label=_('Username'), max_length=30)
    password = forms.CharField(label=_('Password'), widget=forms.PasswordInput())

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(LoginForm, self).__init__(*args, **kwargs)

    def clean(self):
        self.cleaned_data = super(LoginForm, self).clean()
        if self._errors:
            return

        user = authenticate(request=self.request,
                            username=self.cleaned_data['username'],
                            password=self.cleaned_data['password'])

        if user:
            if user.is_active:
                self.user = user
            else:
                raise forms.ValidationError(
                    _('Your account is not activated. Check your email for an activation link.'))
        else:
            raise forms.ValidationError(
                _('The username and/or password you entered are incorrect.'))
        return self.cleaned_data

    def login(self, request):
        if self.is_valid():
            login(request, self.user)
            request.session.set_expiry(settings.LOGIN_EXPIRATION)
            return True
        return False


class RegistrationForm(forms.Form):

    username = forms.RegexField(regex=r'^\w+$', max_length=30, label=_('Username'))
    email1 = forms.EmailField(label=_('Email'))
    email2 = forms.EmailField(label=_('Verify Email'))
    password1 = forms.CharField(widget=forms.PasswordInput(render_value=False), label=_('Password'),
                                help_text=_('Must have at least 8 characters, a letter, and a number'))
    password2 = forms.CharField(widget=forms.PasswordInput(render_value=False), label=_('Verify Password'))
    title = forms.ChoiceField(choices=settings.TITLE_CHOICES, required=False, label=_('Title'))
    first_name = forms.CharField(max_length=30, label=_('First Name'))
    last_name = forms.CharField(max_length=30, label=_('Last Name'))
    date_of_birth = forms.DateField(required=False, input_formats=['%m/%d/%Y'], label=_('Date of Birth'),
                                    help_text=_('Must be formatted as MM/DD/YYYY'))
    gender = forms.ChoiceField(choices=settings.GENDER_CHOICES, required=False, label=_('Gender'))
    company = forms.CharField(max_length=50, required=False, label=_('Company / School / University'))
    phone = forms.RegexField(regex=r'^[0-9]+$', max_length=10, required=False, label=_('Phone Number'),
                             help_text=_('Must not have any spaces, paranthesis, or dashes'))
    address1 = forms.CharField(max_length=150, required=False, label=_('Address Line 1'),
                               help_text=_('Street address, P.O. box'))
    address2 = forms.CharField(max_length=150, required=False, label=_('Address Line 2'),
                               help_text=_('Apartment, suite, unit, building, floor'))
    city = forms.CharField(max_length=30, required=False, label=_('City'))
    state = forms.CharField(max_length=30, required=False, label=_('State / Region / Province'))
    zipcode = forms.CharField(max_length=10, required=False, widget=forms.TextInput(), label=_('ZIP / Postal Code'))
    country = CountryField(blank=True, blank_label='').formfield()
    time_zone = forms.ChoiceField(choices=TIMEZONES, label=_('Time Zone'))
    language = forms.ChoiceField(label=_('Language'), choices=settings.LANGUAGES)
    captcha = CaptchaField(label=_('CAPTCHA'), widget=CaptchaTextInput(),
                           help_text=_('Type the letters you see in the box above.'))
    tos = forms.BooleanField(widget=forms.CheckboxInput(), label=_('I agree to the Terms of Service'),
                             error_messages={'required': 'You must agree to the Terms of Service to proceed.'})

    def clean_username(self):
        if User.objects.filter(username__iexact=self.cleaned_data['username']).count() > 0:
            raise forms.ValidationError(_('This username is not available.'))
        return self.cleaned_data['username']

    def clean_email1(self):
        if User.objects.filter(email__iexact=self.cleaned_data['email1']):
            raise forms.ValidationError(_('This email is already in use.'))
        self.cleaned_data['email1'] = self.cleaned_data['email1'].lower()
        return self.cleaned_data['email1']

    def clean_email2(self):
        self.cleaned_data['email2'] = self.cleaned_data['email2'].lower()
        return self.cleaned_data['email2']

    def clean_password1(self):
        password1 = self.cleaned_data.get('password1')
        if settings.PASSWORD_REGEX:
            if not re.match(settings.PASSWORD_REGEX, password1):
                raise forms.ValidationError(mark_safe(
                    _('The password needs to have at least 8 characters, a letter, and a number.')))

        return password1

    def clean(self):
        if 'password1' in self.cleaned_data and 'password2' in self.cleaned_data:
            if self.cleaned_data['password1'] != self.cleaned_data['password2']:
                raise forms.ValidationError(
                    _('The passwords do not match.'))

        if 'email1' in self.cleaned_data and 'email2' in self.cleaned_data:
            if self.cleaned_data['email1'] != self.cleaned_data['email2']:
                raise forms.ValidationError(_('The emails do not match.'))

        if self._errors:
            return

        return self.cleaned_data

    def save(self, profile_callback=None):
        """
        This is essentially a light wrapper around
        ``RegistrationProfile.objects.create_inactive_user()``,
        feeding it the form data and a profile callback(see the
        documentation on ``create_inactive_user()`` for details) if
        supplied.

        """
        new_user = User.objects.create_user(self.cleaned_data['username'],
                                            self.cleaned_data['email1'],
                                            self.cleaned_data['password1'])

        new_user.first_name = self.cleaned_data['first_name']
        new_user.last_name = self.cleaned_data['last_name']
        new_user.is_active = True
        new_user.save()
        """
        new_profile = Profile(user=new_user,
                              company=self.cleaned_data['company'],
                              phone=self.cleaned_data['phone'],
                              address=self.cleaned_data['address'],
                              city=self.cleaned_data['city'],
                              state=self.cleaned_data['state'],
                              country=self.cleaned_data['country'],
                              zipcode=self.cleaned_data['zipcode'],
                              )

        new_profile.creator = new_user
        new_profile.creator_username = new_user.username
        new_profile.owner = new_user
        new_profile.owner_username = new_user.username
        new_profile.save()
        """
        return new_user


class PasswordResetForm(forms.Form):
    email = forms.EmailField(label=_("Email"))

    def clean_email(self):
        email = self.cleaned_data["email"]
        self.email = email
        try:
            self.user_cache = User.objects.get(email=email.lower(), is_active=True)
        except User.DoesNotExist:
            raise forms.ValidationError(_('The email is not associated with any active accounts.'))
        return email

    def save(self, email_template_name='registration/password_reset_email_user_list.html', **kwargs):
        """
        Generates a one-use only link for resetting password and sends to the designated email.
        The email will contain links for resetting passwords for all accounts associated to the email.
        """
        domain_override = kwargs.get('domain_override', False)
        use_https = kwargs.get('use_https', False)
        token_generator = kwargs.get(
            'token_generator', default_token_generator)

        user_to = {'uid': urlsafe_base64_encode(force_bytes(self.user_cache.pk)),
                   'user': self.user_cache,
                   'token': token_generator.make_token(self.user_cache)}
        t = loader.get_template(email_template_name)
        c = {
            'email': self.email,
            'site_url': settings.SITE_NAME,
            'site_name': site_name,
            'user_list': user_to,
            'protocol': use_https and 'https' or 'http',
        }

        from_email = settings.DEFAULT_FROM_EMAIL
        email = Email(
            sender=from_email,
            recipient=user.email,
            subject=_("Password reset for %s") % settings.SITE_NAME,
            body=t.render(context=c))
        email.send()


class PasswordChangeForm(SetPasswordForm):
    def __init__(self, *args, **kwargs):
        super(PasswordChangeForm, self).__init__(*args, **kwargs)

libreorganize/apps/accounts/views.py
from django.conf import settings
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.views import PasswordResetView
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.decorators import login_required

from apps.accounts.forms import LoginForm, RegistrationForm
from apps.accounts.forms import PasswordResetForm, PasswordChangeForm
from core.decorators import ssl_required


@ssl_required
def login_view(request, form_class=LoginForm, template_name="login.html"):

    redirect_to = request.GET.get('next', '')

    if request.method == "POST":

        # Make sure redirect_to isn't garabage
        if not redirect_to or "://" in redirect_to or " " in redirect_to:
            redirect_to = reverse('home')  # PROFILE

        form = form_class(request.POST, request=request)
        if form.login(request):
            messages.add_message(request, messages.SUCCESS,
                                 _('Welcome back, %(FIRST_NAME)s! You have successfully logged in.') %
                                 {'FIRST_NAME': request.user.first_name})
            return HttpResponseRedirect(redirect_to)
    else:
        form = form_class(request=request)

        if request.user.is_authenticated and redirect_to:
            return HttpResponseRedirect(redirect_to)
        elif request.user.is_authenticated:
            messages.add_message(request, messages.WARNING,
                                 _('You are already logged in as %(FIRST_NAME)s! (%(EMAIL)s)') %
                                 {'FIRST_NAME': request.user.first_name, 'EMAIL': request.user.email})
            return HttpResponseRedirect(reverse('home'))  # PROFILE

    return render(request=request, template_name=template_name, context={"form": form})


@ssl_required
def logout_view(request, template_name='logout.html'):
    if request.user.is_authenticated:
        messages.add_message(request, messages.SUCCESS,
                             _('You have successfully logged out.'))
    else:
        messages.add_message(request, messages.WARNING,
                             _('You are already logged out.'))
    logout(request)
    return HttpResponseRedirect(reverse('home'))


@ssl_required
def register_view(request, form_class=RegistrationForm, template_name='register.html'):

    form_params = {}
    if request.session.get('form_params', None):
        form_params = request.session.pop('form_params')

    if request.method == 'POST':
        form = form_class(data=request.POST, **form_params)
        if form.is_valid():
            new_user = form.save()
            messages.add_message(request, messages.SUCCESS, _("Welcome to %(SITE_NAME)s, %(FIRST_NAME)s! You have successfully registered.") %
                                 {'SITE_NAME': settings.SITE_NAME, 'FIRST_NAME': form.cleaned_data['first_name']})
            new_user = authenticate(request=request, username=form.cleaned_data['username'], password=form.cleaned_data['password1'])
            login(request, new_user)
            request.session.set_expiry(settings.LOGIN_EXPIRATION)
            return HttpResponseRedirect(reverse('home'))
    else:
        request.session['form_params'] = form_params
        form = form_class(**form_params)

    if request.user.is_authenticated:
        messages.add_message(request, messages.WARNING, _("You are already logged in as %(FIRST_NAME)s! You cannot register an account while being logged in.") %
                             {'FIRST_NAME': request.user.first_name})
        return HttpResponseRedirect(reverse('home'))

    return render(request=request, template_name=template_name, context={'form': form})


def password_reset_view(request):
    auth_password_reset = PasswordResetView.as_view(form_class=PasswordResetForm,
                                                    template_name='password_reset.html',
                                                    email_template_name='registration/password_reset_email_user_list.html')
    return auth_password_reset(request)


@ssl_required
@login_required
def password_change_view(request, id, template_name='password_change.html', password_change_form=PasswordChangeForm):
    user = get_object_or_404(User, pk=id)
    if request.method == "POST":
        form = password_change_form(user=user, data=request.POST)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS, _("You have successfully changed your password. Please log in again."))
            return HttpResponseRedirect(reverse('home'))  # PROFILE
    else:
        form = password_change_form(user=user)
    return render(request=request, template_name=template_name, context={
        'user_this': user,
        'form': form,
    })


@login_required
def password_change_done_view(request, id, template_name='password_reset_send.html'):
    user_edit = get_object_or_404(User, pk=id)
    return render(request=request, template_name=template_name, context={'user_this': user_edit})

libreorganize/apps/accounts/templates/login.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block extra_head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
{% endblock %}

{% block content %}
<div class="row no-gutters h-100 card-row">
    <div class="col-lg-6 offset-lg-3 col-sm-8 offset-sm-2 col-10 offset-1 my-auto">
        <div class="card text-white mx-auto">
            <div class="card-header">
                <h1 class="text-center black">{% trans "LOG IN" %}</h1>
            </div>
            <div class="card-body black">
                <form id="login-form" method="post">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <div class="form-group text-center">
                        <div class="col-md-12">
                            <button type="submit" class="btn btn-primary btn-accounts">{% trans "Log in" %}</button>
                            <a href="{% url 'accounts:register' %}"
                                class="btn btn-secondary btn-accounts">{% trans "Register" %}</a>
                        </div>
                    </div>
                </form>
            </div>
            <div class="card-footer text-center">
                <a href="{% url 'accounts:reset_password' %}">{% trans "Forgot your password?" %}</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

libreorganize/apps/accounts/templates/password_change.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block extra_head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/reset_password.css' %}">
{% endblock %}

{% block content %}
<div class="row no-gutters h-100 card-row">
    <div class="col-lg-6 offset-lg-3 col-sm-8 offset-sm-2 col-10 offset-1 my-auto">
        <div class="card text-white mx-auto">
            <div class="card-header">
                <h1 class="text-center black">{% trans "CHANGE PASSWORD" %}</h1>
            </div>
            <div class="card-body black">
                <form id="login-form" method="post">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <div class="form-group text-center">
                        <div class="col-md-12">
                            <button type="submit" class="btn btn-primary btn-accounts">{% trans "Submit" %}</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

libreorganize/apps/accounts/templates/password_reset.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block extra_head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/reset_password.css' %}">
{% endblock %}

{% block content %}
{% if not user.is_authenticated %}
<div class="row no-gutters h-100 card-row">
    <div class="col-lg-6 offset-lg-3 col-sm-8 offset-sm-2 col-10 offset-1 my-auto">
        <div class="card text-white mx-auto">
            <div class="card-header">
                <h1 class="text-center black">{% trans "RESET PASSWORD" %}</h1>
            </div>
            <div class="card-body black">
                <form id="login-form" method="post">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <div class="form-group text-center">
                        <div class="col-md-12">
                            <button type="submit" class="btn btn-primary btn-accounts">{% trans "Submit" %}</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

{% else %}
<div class="row no-gutters h-100 card-row">
    <div class="col-lg-6 offset-lg-3 col-sm-8 offset-sm-2 col-10 offset-1 my-auto">
        <div class="card text-white mx-auto">
            <div class="card-header">
                <h1 class="text-center black">{% trans "CHANGE PASSWORD" %}</h1>
            </div>
            <div class="card-body black">
                <form id="login-form" method="post">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <div class="form-group text-center">
                        <div class="col-md-12">
                            <button type="submit" class="btn btn-primary btn-accounts">{% trans "Submit" %}</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

libreorganize/apps/accounts/templates/password_reset_send.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block extra_head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/logout.css' %}">
{% endblock %}

{% block content %}
{% if not user.is_authenticated %}
<div class="row no-gutters h-100 card-row">
    <div class=" col-lg-6 offset-lg-3 col-sm-8 offset-sm-2 col-10 offset-1 my-auto">
        <div class="card text-white">
            <div class="card-header">
                <h1 class="text-centerblack">{% trans "RESET PASSWORD" %}</h1>
            </div>
            <div class="card-body text-center black">
                <div class="col-md-12">
                    <p style="margin-bottom: 8px;">{% blocktrans %}An email containing the reset link has been sent
                        to{% endblocktrans %} {{ email }}!</p>
                </div>
            </div>
        </div>
    </div>
</div>

{% else %}
<div class="row no-gutters h-100 card-row">
    <div class=" col-lg-6 offset-lg-3 col-sm-8 offset-sm-2 col-10 offset-1 my-auto">
        <div class="card text-white">
            <div class="card-header">
                <h1 class="text-center black">{% trans "CHANGE PASSWORD" %}</h1>
            </div>
            <div class="card-body text-center black">
                <div class="col-md-12">
                    <p style="margin-bottom: 8px;">{% blocktrans %}Your password has been succesfully
                        changed!{% endblocktrans %}</p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

libreorganize/apps/accounts/templates/register.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block extra_head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/register.css' %}">
{% endblock %}

{% block content %}
<div class="row no-gutters h-100 card-row">
    <div class="col-lg-6 offset-lg-3 col-sm-8 offset-sm-2 col-10 offset-1 my-auto">
        <div class="card text-white mx-auto">
            <div class="card-header">
                <h1 class="text-center black">{% trans "REGISTER" %}</h1>
            </div>
            <div class="card-body black">
                <form id="login-form" method="post">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <div class="form-group text-center">
                        <div class="col-md-12">
                            <button type="submit" class="btn btn-primary btn-accounts">{% trans "Submit" %}</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}