libreorganize/apps/accounts/urls.py
from django.urls import path, re_path
from django.contrib.auth.views import PasswordResetConfirmView, PasswordResetCompleteView, PasswordResetDoneView
from django.views.generic import TemplateView

from apps.accounts import views, forms

app_name = 'apps.accounts'

urlpatterns = [
    path('login/', views.login_view, name='login'),

    path('logout/', views.logout_view, name='logout'),

    path('register/', views.register_view, name='register'),

    re_path(r'^password/change/(?P<id>\d+)/$', views.password_change_view, name='change_password'),

    re_path(r'^password/change/done/(?P<id>\d+)/$', views.password_change_done_view, name='change_password_done'),

    path('password/reset/', views.password_reset_view, name='reset_password'),

    re_path(r'^password/reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$',
            PasswordResetConfirmView.as_view(template_name='registration/custom_password_reset_confirm.html', form_class=forms.PasswordChangeForm),
            name='reset_password_confirmation'),

    path('password/reset/complete/', PasswordResetCompleteView.as_view(template_name='registration/custom_password_reset_complete.html'),
         name='reset_password_complete'),

    path('password/reset/done/', PasswordResetDoneView.as_view(template_name='registration/custom_password_reset_done.html'),
         name='reset_password_done'),

    path('register/complete/', TemplateView.as_view(template_name='accounts/registration_complete.html'),
         name='register_complete'),
]

libreorganize/core/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name="home.html"), name='home'),
    path('accounts/', include('apps.accounts.urls', namespace='accounts')),
    re_path(r'^captcha/', include('captcha.urls')),
]

libreorganize/templates/base.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script defer src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,500&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
    <script type="text/javascript" src="{% static 'js/base.js' %}"></script>
    {% if title %}
    <title>{{ title }} | LibreOrganize</title>
    {% else %}
    <title>LibreOrganize</title>
    {% endif %}
    {% block extra_head %}{% endblock %}
</head>

<header>
    <nav class="navbar fixed-top navbar-expand-md navbar-dark" id="navbar">
        <a class="navbar-brand"><img class="navbar-brand-img" src="{% static 'img/website_logo.png' %}"></a>
        <div id="core-button-div">
            {% if not user.is_authenticated %}
            <a class="core-button" href="{% url 'accounts:login' %}"><img src="{% static 'img/login_icon.png' %}"></a>
            {% else %}
            <a class="core-button" id="open-dashboard" href="javascript:void(0);"><img
                    src="{% static 'img/dashboard_icon.png' %}"></a>
            <a class="core-button" href="{% url 'accounts:login' %}"><img src="{% static 'img/profile_icon.png' %}"></a>
            <a class="core-button" href="{% url 'accounts:logout' %}"><img src="{% static 'img/logout_icon.png' %}"></a>
            {% endif %}
            <a class="core-button hide-desktop" href="javascript:void(0);" data-toggle="collapse"
                data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup">
                <img src="{% static 'img/menu_icon.png' %}">
            </a>
        </div>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav ml-auto">
                <a class="nav-item nav-link" href="/">{% trans "Home" %}</a>
            </div>
        </div>
    </nav>
    {% if messages %}
    <ul class="fixed-top">
        {% for message in messages %}
        <li class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            {{ message }}
        </li>
        {% endfor %}
    </ul>
    {% endif %}
</header>

<div id="dashboard" class="dashboard hide">
    <div class="dashboard-header">
        <p>Welcome to the Dashboard, <span>{{ user.first_name }}</span>!</p>
        <a class="core-button" id="close-dashboard" href="javascript:void(0)"><img
                src="{% static 'img/close_icon.png' %}"></a>
    </div>

    <div class="dashboard-content">
        <a href="https://gitlab.com/libreorganize/libreorganize-v2/issues/new">{% trans "Report a bug" %}</a>
    </div>
</div>

<body>
    {% block content %}{% endblock %}
</body>

<footer>
    <div class="text-center footer-logos">
        <p>Developed and Powered by</p>
        <div class="div-logo">
            <a href="https://novawebdevelopment.com/"><img src="{% static 'img/nwd_logo.png' %}"></a>
            <a href="https://libreorganize.org/"><img src="{% static 'img/libreorganize_logo.png' %}"></a>
        </div>
        <p>Copyright &copy; 2020 | Licensed under Creative Commons Attribution - No Derivative Works 3.0 License
            (or later version)</p>
    </div>
</footer>

</html>

libreorganize/templates/home.html
{% extends "base.html" %}
{% load static %}

{% block extra_head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %}">
{% endblock %}

{% block content %}
<div class="home">
    <div id="text-center-home">
        <h1>Welcome to the LibreOrganize DEMO!</h1>
    </div>
</div>
{% endblock %}